### ISSUE TITLE
关于人工智能的建议

### ISSUE THREAD

**Issue by chainsx** [Erblocker/atulocher#6]
飞哥，
我现在联系了学校科技社管理崔老师，
他说可能要用树莓派或者Arduino来DIY机器人，
可否在人工智能方面提供支持？

**Comment by cgoxopx** [comment]
图形识别？

**Comment by cgoxopx** [comment]
如果是图形识别，可以用 Tencent的ncnn 。这东西在arm上表现非常好，只是不支持线上训练（也就是说运行和学习不能同时进行）。  
其他机器学习框架，大多数在树莓派上编译不了。  
因为树莓派的GPU接口是opencl，而大多数框架用的是cuda

**Comment by chainsx** [comment]
OK

**Comment by cgoxopx** [comment]
你们做的是个什么项目？    
我3d打印机到货了（某宝上的，reprap i3的机器，三位数价钱的）  
具体能不能正常工作……我也不清楚，只知道电路以及固件没问题。  
************
另外教室电脑的显卡不错，适合训练ai，装个caffe，晚上悄悄地开一通宵……

**Comment by chainsx** [comment]
教室电脑不是i7核显吗？

**Comment by cgoxopx** [comment]
跑caffe。的确跑得挺快。  
我们高三这边，两台电脑。主机一台，大屏幕自带一台（不清楚性能如何）。

**Comment by chainsx** [comment]
那个大屏幕好像是i3，性能不咋地

**Comment by cgoxopx** [comment]
那个psychic，可以在arm上跑，并且支持opencl加速  
我用别人的[项目](https://github.com/artix75/psyc.git)改造的。  
但是目前对opencl支持得并不彻底，只对lstm做了一点优化。  
不过完全用cpu跑也不是问题。
